// ollis-astro-club--nuxt/app/pages/[locale]/fun/videos.vue
<script setup lang="ts">
const supportedLocales = ['de', 'en'] as const;
type SupportedLocale = (typeof supportedLocales)[number];

const route = useRoute();
const routeLocale = computed(() => typeof route.params.locale === 'string' ? route.params.locale : '');

if (!supportedLocales.includes(routeLocale.value as SupportedLocale)) {
  throw createError({ statusCode: 404, statusMessage: 'Page not found' });
}

const { t, locale } = useI18n();
locale.value = routeLocale.value;

useHead({ title: t('fun.videos') });
</script>

<template>
  <div class="space-y-6">
    <h1 class="font-heading text-3xl font-bold text-[var(--foreground)]">{{ t('fun.videos') }}</h1>
    <p class="font-body text-lg text-[var(--foreground)] opacity-70">
      {{ routeLocale === 'de' ? 'Videos kommen bald! 🎬' : 'Videos are coming soon! 🎬' }}
    </p>
  </div>
</template>

// ollis-astro-club-next-js/app/[locale]/fun/videos/page.tsx
import { useTranslations } from 'next-intl';

export default function VideosPage() {
  const t = useTranslations('fun');

  return (
    <div className="space-y-6">
      <h1 className="font-heading text-3xl font-bold">{t('videos')}</h1>
      <p className="font-body text-lg opacity-70">Videos kommen bald! 🎬</p>
    </div>
  );
}
