// app/pages/[locale]/dashboard.vue
<script setup lang="ts">
const supportedLocales = ['de', 'en'] as const;
type SupportedLocale = (typeof supportedLocales)[number];

const route = useRoute();
const routeLocale = computed(() => typeof route.params.locale === 'string' ? route.params.locale : '');

if (!supportedLocales.includes(routeLocale.value as SupportedLocale)) {
  throw createError({ statusCode: 404, statusMessage: 'Page not found' });
}

const { t, locale } = useI18n();
locale.value = routeLocale.value;

useHead({ title: `🔒 ${t('dashboard.title')}` });
</script>

<template>
  <div class="space-y-6">
    <h1 class="font-heading text-3xl font-bold text-[var(--foreground)]">🔒 {{ t('dashboard.title') }}</h1>
    <p class="font-body text-lg text-[var(--foreground)] opacity-70">
      {{ routeLocale === 'de' ? 'Der Benutzerbereich wird bald verfuegbar sein!' : 'The member area will be available soon!' }}
    </p>
  </div>
</template>

// ollis-astro-club-next-js/app/[locale]/dashboard/page.tsx
import { useTranslations } from 'next-intl';

export default function DashboardPage() {
  const t = useTranslations('dashboard');

  return (
    <div className="space-y-6">
      <h1 className="font-heading text-3xl font-bold">🔒 {t('title')}</h1>
      <p className="font-body text-lg opacity-70">
        Der Benutzerbereich wird bald verfügbar sein!
      </p>
    </div>
  );
}
