// ollis-astro-club-next-js/app/[locale]/games/asteroids/page.tsx
import { useTranslations } from 'next-intl';

export default function AsteroidsPage() {
  const t = useTranslations('games');

  return (
    <div className="space-y-6">
      <h1 className="font-heading text-3xl font-bold">☄️ {t('asteroids.title')}</h1>
      <p className="font-body text-lg opacity-70">Asteroids kommt bald! 🎮</p>
    </div>
  );
}

// app/pages/[locale]/games/asteroids.vue
<script setup lang="ts">
const supportedLocales = ['de', 'en'] as const;
type SupportedLocale = (typeof supportedLocales)[number];

const route = useRoute();
const routeLocale = computed(() => typeof route.params.locale === 'string' ? route.params.locale : '');

if (!supportedLocales.includes(routeLocale.value as SupportedLocale)) {
  throw createError({ statusCode: 404, statusMessage: 'Page not found' });
}

const { t, locale } = useI18n();
locale.value = routeLocale.value;

useHead({ title: `☄️ ${t('games.asteroids.title')}` });
</script>

<template>
  <div class="space-y-6">
    <h1 class="font-heading text-3xl font-bold text-[var(--foreground)]">☄️ {{ t('games.asteroids.title') }}</h1>
    <p class="font-body text-lg text-[var(--foreground)] opacity-70">
      {{ routeLocale === 'de' ? 'Asteroids kommt bald! 🎮' : 'Asteroids is coming soon! 🎮' }}
    </p>
  </div>
</template>
